{% set version = "0.8" %}

package:
  name: terminado
  version: {{ version }}

source:
  fn: terminado-{{ version }}.tar.gz
  url: https://github.com/takluyver/terminado/archive/0.6.tar.gz
  sha256: 984c914303fcd1642c1783cdc6727db24b0bc1494fa6363e6ae46696335e2944

build:
  number: 0
  script: python setup.py install
  skip: True  # [win and py27]

requirements:
  build:
    - python
  run:
    - python
    - ptyprocess  # [not win]
    - pywinpty  # [win]
    - tornado >=4

test:
  imports:
    - terminado

  requires:
    - nose

  commands:
    # Failing test on osx: https://github.com/conda-forge/staged-recipes/pull/313#issuecomment-208426267
    - nosetests terminado  # [not osx]

about:
  home: http://github.com/mitsuhiko/markupsafe
  license: BSD 3-clause
  summary: Terminals served by tornado websockets

extra:
  recipe-maintainers:
    - blink1073
    - pelson
    - takluyver 
